# alacritty color scheme

schemes:
  tender: &tender
     primary:
       background: '0x282828'
        foreground: '0xeeeeee'

      # Normal colors
      normal:
        black:   '0x282828'
        red:     '0xf43753'
        green:   '0xc9d05c'
        yellow:  '0xffc24b'
        blue:    '0xb3deef'
        magenta: '0xd3b987'
        cyan:    '0x73cef4'
        white:   '0xeeeeee'

      # Bright colors
      bright:
        black:   '0x4c4c4c'
        red:     '0xf43753'
        green:   '0xc9d05c'
        yellow:  '0xffc24b'
        blue:    '0xb3deef'
        magenta: '0xd3b987'
        cyan:    '0x73cef4'
        white:   '0xfeffff'
  gruvbox: &gruvbox
      primary:
        background: '0x1d2021'
        foreground: '0xfbf1c7'
        normal:
        black:   '0x282828'
        red:     '0xfb4934'
        green:   '0xb8bb26'
        yellow:  '0xfabd2f'
        blue:    '0x83a598'
        magenta: '0xd3869b'
        cyan:    '0x8ec07c'
        white:   '0xfbf1c7'
      bright:
        black:   '0x32302f'
        red:     '0xea6962'
        green:   '0xa9b665'
        yellow:  '0xffc745'
        blue:    '0x7daea3'
        magenta: '0xd3869b'
        cyan:    '0x89b482'
        white:   '0xf9f5d7'

  shades: &serenade
      primary:
        background: '#2A2F33'
        foreground: '#bfddb2'
      cursor:
        text: '#bfddb2'
        cursor: '#2E3338'
      normal:
        black: '#000000'
        red: '#d76e6e'
        green: '#ACB765'
        yellow: '#c1bf89'
        blue: '#82abbc'
        magenta: '#FF628C'
        cyan: '#9EFFFF'
        white: '#DBDBE0'
      bright:
        black: '#5C5C61'
        red: '#d76e6e'
        green: '#ACB765'
        yellow: '#FAD000'
        blue: '#82abbc'
        magenta: '#FF628C'
        cyan: '#9EFFFF'
        white: '#FFFFFF'

  shades: &onedark
      primary:
        background: '#1e222a'
        foreground: '#abb2bf'
      normal:
        black: '#5c6370'
        red: '#e06c75'
        green: '#98c379'
        yellow: '#e5c07b'
        blue: '0x61afef'
        magenta: '#c678dd'
        cyan: '#56b6c2'
        white: '#abb2bf'
      bright:
        black: '#4b5263'
        red: '#e06c75'
        green: '#98c379'
        yellow: '#e5c07b'
        blue: '0x61afef'
        magenta: '#c678dd'
        cyan: '#56b6c2'
        white: '#abb2bf'

colors: *tender
